// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppCleanArch.Infrastructure.Data;

#nullable disable

namespace WebAppCleanArch.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251225000243_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppCleanArch.Domain.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 1,
                            Status = "Present",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            AttendanceDate = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 1,
                            Status = "Present",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            AttendanceDate = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 1,
                            Notes = "Family emergency",
                            Status = "Absent",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 4,
                            AttendanceDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 1,
                            Status = "Present",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 5,
                            AttendanceDate = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 1,
                            Notes = "Flu",
                            Status = "Sick",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 6,
                            AttendanceDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 2,
                            Status = "Present",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 7,
                            AttendanceDate = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 2,
                            Status = "Present",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 8,
                            AttendanceDate = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 2,
                            Status = "Present",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 9,
                            AttendanceDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 2,
                            Notes = "Doctor appointment",
                            Status = "Permission",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 10,
                            AttendanceDate = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 2,
                            Status = "Present",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 11,
                            AttendanceDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 3,
                            Status = "Present",
                            StudentId = 5
                        },
                        new
                        {
                            Id = 12,
                            AttendanceDate = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 3,
                            Status = "Present",
                            StudentId = 5
                        },
                        new
                        {
                            Id = 13,
                            AttendanceDate = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 3,
                            Status = "Present",
                            StudentId = 5
                        },
                        new
                        {
                            Id = 14,
                            AttendanceDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 3,
                            Notes = "No reason provided",
                            Status = "Absent",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 15,
                            AttendanceDate = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CourseId = 3,
                            Status = "Present",
                            StudentId = 6
                        });
                });

            modelBuilder.Entity("WebAppCleanArch.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Instructor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCode = "WEB101",
                            CourseName = "Web Programming",
                            Description = "Introduction to web development using HTML, CSS, and JavaScript",
                            Instructor = "Dr. John Smith"
                        },
                        new
                        {
                            Id = 2,
                            CourseCode = "MOB201",
                            CourseName = "Mobile Application Development",
                            Description = "Building mobile apps for Android and iOS",
                            Instructor = "Prof. Sarah Johnson"
                        },
                        new
                        {
                            Id = 3,
                            CourseCode = "DB301",
                            CourseName = "Database Management",
                            Description = "Database design and SQL programming",
                            Instructor = "Dr. Michael Brown"
                        },
                        new
                        {
                            Id = 4,
                            CourseCode = "SE401",
                            CourseName = "Software Engineering",
                            Description = "Principles and practices of software development",
                            Instructor = "Prof. Emily Davis"
                        },
                        new
                        {
                            Id = 5,
                            CourseCode = "DSA301",
                            CourseName = "Data Structures and Algorithms",
                            Description = "Advanced data structures and algorithm analysis",
                            Instructor = "Dr. Robert Wilson"
                        });
                });

            modelBuilder.Entity("WebAppCleanArch.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            EnrollmentDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            EnrollmentDate = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 95.5m,
                            Status = "Completed",
                            StudentId = 5
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 3,
                            EnrollmentDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 1,
                            EnrollmentDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 4,
                            EnrollmentDate = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 5,
                            EnrollmentDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 8
                        });
                });

            modelBuilder.Entity("WebAppCleanArch.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jl. Merdeka No. 123, Jakarta",
                            CourseId = 1,
                            Email = "alice.anderson@example.com",
                            Name = "Alice Anderson",
                            PhoneNumber = "081234567890"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Jl. Sudirman No. 456, Bandung",
                            CourseId = 1,
                            Email = "bob.baker@example.com",
                            Name = "Bob Baker",
                            PhoneNumber = "081234567891"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Jl. Gatot Subroto No. 789, Surabaya",
                            CourseId = 2,
                            Email = "charlie.chen@example.com",
                            Name = "Charlie Chen",
                            PhoneNumber = "081234567892"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Jl. Ahmad Yani No. 321, Yogyakarta",
                            CourseId = 2,
                            Email = "diana.davis@example.com",
                            Name = "Diana Davis",
                            PhoneNumber = "081234567893"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Jl. Diponegoro No. 654, Semarang",
                            CourseId = 3,
                            Email = "edward.evans@example.com",
                            Name = "Edward Evans",
                            PhoneNumber = "081234567894"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Jl. Pemuda No. 987, Malang",
                            CourseId = 3,
                            Email = "fiona.fisher@example.com",
                            Name = "Fiona Fisher",
                            PhoneNumber = "081234567895"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Jl. Pahlawan No. 147, Medan",
                            CourseId = 4,
                            Email = "george.garcia@example.com",
                            Name = "George Garcia",
                            PhoneNumber = "081234567896"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Jl. Veteran No. 258, Makassar",
                            CourseId = 5,
                            Email = "hannah.harris@example.com",
                            Name = "Hannah Harris",
                            PhoneNumber = "081234567897"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Jl. Raya No. 369, Palembang",
                            Email = "ivan.ibrahim@example.com",
                            Name = "Ivan Ibrahim",
                            PhoneNumber = "081234567898"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Jl. Proklamasi No. 741, Denpasar",
                            Email = "jessica.jones@example.com",
                            Name = "Jessica Jones",
                            PhoneNumber = "081234567899"
                        });
                });

            modelBuilder.Entity("WebAppCleanArch.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("WebAppCleanArch.Domain.Entities.Course", "Course")
                        .WithMany("Attendances")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppCleanArch.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WebAppCleanArch.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("WebAppCleanArch.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppCleanArch.Domain.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WebAppCleanArch.Domain.Entities.Student", b =>
                {
                    b.HasOne("WebAppCleanArch.Domain.Entities.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WebAppCleanArch.Domain.Entities.Course", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Enrollments");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("WebAppCleanArch.Domain.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
